### PR TITLE
bug fix - only put raw tags into templates when using foundation

### PR DESCRIPTION
**Pull request by stephenmoloney**
#### Problem:

Raw tags are needed when using inky templates to ignore elixirs' `<%= %>` tags.... but this 
should only be used when using the inky templates... otherwise, those `<raw>` tags are not required.

This PR fixes it.

### CODE REVIEW

**Comment by stephenmoloney** [comment]
I noticed your recent commit...  I will close this PR.

**Comment by jfrolich** [comment]
Can we not enclose them in brackets{{{}}}?

**Comment by stephenmoloney** [comment]
I haven;t got a chance to download your branch yet to test it but when I was testing my branch, I had to wrap the eex tags in `<raw>` tags for the inky template conversions because somehow the inky library was modifying the `<%=` and `%>` tags.... by wrapping it in `<raw>` before putting it through inky, it stopped this from happening.... 

you can see foundation's own tests [here](https://github.com/zurb/inky/blob/39a43c34a09e47a00146ca107c7f7d2e7e9a7f2c/test/inky.js#L90)

I'll try to get to download these changes soon and try them out...

**Comment by stephenmoloney** [comment]
as far as i can tell so far, the `{{{}}}` brackets seem to work also - so no need for `<raw>` anymore i guess.

**Pull request closed without merging**
